//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVc_Assignment2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public int UserId { get; set; }
        public string Cart { get; set; }
        public string CCName { get; set; }
        public string CCNumber { get; set; }
        public Nullable<decimal> Payment { get; set; }
        public int Status { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string Address { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
        public string City { get; set; }
        public string CCV { get; set; }
        public string CCDate { get; set; }
    }
}
